# state marineLocomotion
# autogenerated by SmartBody

stateManager = scene.getStateManager()

statemarineLocomotion = stateManager.createState3D("ChrMarineLocomotion")

motions = StringVec()
motions.append("ChrBrad_ChrMarine@Idle01")
motions.append("ChrBrad_ChrMarine@Jog01")
motions.append("ChrBrad_ChrMarine@Meander01")
motions.append("ChrBrad_ChrMarine@Run01")
# motions.append("ChrBrad_ChrMarine@RunCircleLf01_smooth")
# motions.append("ChrBrad_ChrMarine@RunCircleRt01_smooth")
motions.append("ChrBrad_ChrMarine@RunCircleLf01_smooth")
motions.append("ChrBrad_ChrMarine@RunCircleRt01_smooth")
motions.append("ChrBrad_ChrMarine@RunTightCircleLf01")
motions.append("ChrBrad_ChrMarine@RunTightCircleRt01")
motions.append("ChrBrad_ChrMarine@StrafeSlowLf01")
motions.append("ChrBrad_ChrMarine@StrafeSlowRt01")
motions.append("ChrBrad_ChrMarine@Walk01")
# motions.append("ChrBrad_ChrMarine@WalkCircleLf01_smooth")
# motions.append("ChrBrad_ChrMarine@WalkCircleRt01_smooth")
# motions.append("ChrBrad_ChrMarine@WalkTightCircleLf01_smooth")
# motions.append("ChrBrad_ChrMarine@WalkTightCircleRt01_smooth")
motions.append("ChrBrad_ChrMarine@WalkCircleLf01_smooth")
motions.append("ChrBrad_ChrMarine@WalkCircleRt01_smooth")
motions.append("ChrBrad_ChrMarine@WalkTightCircleLf01_smooth")
motions.append("ChrBrad_ChrMarine@WalkTightCircleRt01_smooth")
motions.append("ChrBrad_ChrMarine@Turn360Lf01")
motions.append("ChrBrad_ChrMarine@Turn360Rt01")
motions.append("ChrBrad_ChrMarine@StrafeFastLf01_smooth")
motions.append("ChrBrad_ChrMarine@StrafeFastRt01_smooth")

paramsX = DoubleVec()
paramsY = DoubleVec()
paramsZ = DoubleVec()
paramsX.append(0) # ChrBrad_ChrMarine@Idle01 X
paramsY.append(0) # ChrBrad_ChrMarine@Idle01 Y
paramsZ.append(0) # ChrBrad_ChrMarine@Idle01 Z
paramsX.append(0) # ChrBrad_ChrMarine@Jog01 X
paramsY.append(0) # ChrBrad_ChrMarine@Jog01 Y
paramsZ.append(0) # ChrBrad_ChrMarine@Jog01 Z
paramsX.append(0) # ChrBrad_ChrMarine@Meander01 X
paramsY.append(0) # ChrBrad_ChrMarine@Meander01 Y
paramsZ.append(0) # ChrBrad_ChrMarine@Meander01 Z
paramsX.append(0) # ChrBrad_ChrMarine@Run01 X
paramsY.append(0) # ChrBrad_ChrMarine@Run01 Y
paramsZ.append(0) # ChrBrad_ChrMarine@Run01 Z
paramsX.append(0) # ChrBrad_ChrMarine@RunCircleLf01_smooth X
paramsY.append(0) # ChrBrad_ChrMarine@RunCircleLf01_smooth Y
paramsZ.append(0) # ChrBrad_ChrMarine@RunCircleLf01_smooth Z
paramsX.append(0) # ChrBrad_ChrMarine@RunCircleRt01_smooth X
paramsY.append(0) # ChrBrad_ChrMarine@RunCircleRt01_smooth Y
paramsZ.append(0) # ChrBrad_ChrMarine@RunCircleRt01_smooth Z
paramsX.append(0) # ChrBrad_ChrMarine@RunTightCircleLf01 X
paramsY.append(0) # ChrBrad_ChrMarine@RunTightCircleLf01 Y
paramsZ.append(0) # ChrBrad_ChrMarine@RunTightCircleLf01 Z
paramsX.append(0) # ChrBrad_ChrMarine@RunTightCircleRt01 X
paramsY.append(0) # ChrBrad_ChrMarine@RunTightCircleRt01 Y
paramsZ.append(0) # ChrBrad_ChrMarine@RunTightCircleRt01 Z
paramsX.append(0) # ChrBrad_ChrMarine@StrafeFastLf01_smooth X
paramsY.append(0) # ChrBrad_ChrMarine@StrafeFastLf01_smooth Y
paramsZ.append(0) # ChrBrad_ChrMarine@StrafeFastLf01_smooth Z
paramsX.append(0) # ChrBrad_ChrMarine@StrafeFastRt01_smooth X
paramsY.append(0) # ChrBrad_ChrMarine@StrafeFastRt01_smooth Y
paramsZ.append(0) # ChrBrad_ChrMarine@StrafeFastRt01_smooth Z
paramsX.append(0) # ChrBrad_ChrMarine@Walk01 X
paramsY.append(0) # ChrBrad_ChrMarine@Walk01 Y
paramsZ.append(0) # ChrBrad_ChrMarine@Walk01 Z
paramsX.append(0) # ChrBrad_ChrMarine@WalkCircleLf01_smooth X
paramsY.append(0) # ChrBrad_ChrMarine@WalkCircleLf01_smooth Y
paramsZ.append(0) # ChrBrad_ChrMarine@WalkCircleLf01_smooth Z
paramsX.append(0) # ChrBrad_ChrMarine@WalkCircleRt01_smooth X
paramsY.append(0) # ChrBrad_ChrMarine@WalkCircleRt01_smooth Y
paramsZ.append(0) # ChrBrad_ChrMarine@WalkCircleRt01_smooth Z
paramsX.append(0) # ChrBrad_ChrMarine@WalkTightCircleLf01_smooth X
paramsY.append(0) # ChrBrad_ChrMarine@WalkTightCircleLf01_smooth Y
paramsZ.append(0) # ChrBrad_ChrMarine@WalkTightCircleLf01_smooth Z
paramsX.append(0) # ChrBrad_ChrMarine@WalkTightCircleRt01_smooth X
paramsY.append(0) # ChrBrad_ChrMarine@WalkTightCircleRt01_smooth Y
paramsZ.append(0) # ChrBrad_ChrMarine@WalkTightCircleRt01_smooth Z
paramsX.append(0) # ChrBrad_ChrMarine@WalkTightCircleLf01_smooth X
paramsY.append(0) # ChrBrad_ChrMarine@WalkTightCircleLf01_smooth Y
paramsZ.append(0) # ChrBrad_ChrMarine@WalkTightCircleLf01_smooth Z
paramsX.append(0) # ChrBrad_ChrMarine@WalkTightCircleRt01_smooth X
paramsY.append(0) # ChrBrad_ChrMarine@WalkTightCircleRt01_smooth Y
paramsZ.append(0) # ChrBrad_ChrMarine@WalkTightCircleRt01_smooth Z

paramsX.append(0) # ChrBrad_ChrMarine@WalkTightCircleLf01_smooth X
paramsY.append(0) # ChrBrad_ChrMarine@WalkTightCircleLf01_smooth Y
paramsZ.append(0) # ChrBrad_ChrMarine@WalkTightCircleLf01_smooth Z
paramsX.append(0) # ChrBrad_ChrMarine@WalkTightCircleRt01_smooth X
paramsY.append(0) # ChrBrad_ChrMarine@WalkTightCircleRt01_smooth Y
paramsZ.append(0) # ChrBrad_ChrMarine@WalkTightCircleRt01_smooth Z

for i in range(0, len(motions)):
	statemarineLocomotion.addMotion(motions[i], paramsX[i], paramsY[i], paramsZ[i])

points0 = DoubleVec()
points0.append(0) # ChrBrad_ChrMarine@Idle01 0
points0.append(0) # ChrBrad_ChrMarine@Jog01 0
points0.append(0.21) # ChrBrad_ChrMarine@Meander01 0
points0.append(0) # ChrBrad_ChrMarine@Run01 0
points0.append(0.12) # ChrBrad_ChrMarine@RunCircleLf01_smooth 0
points0.append(0.52) # ChrBrad_ChrMarine@RunCircleRt01_smooth 0
points0.append(0.51) # ChrBrad_ChrMarine@RunTightCircleLf01 0
points0.append(0.04) # ChrBrad_ChrMarine@RunTightCircleRt01 0
points0.append(0.90) # ChrBrad_ChrMarine@StrafeSlowLf01 0
points0.append(0.44) # ChrBrad_ChrMarine@StrafeSlowRt01 0
points0.append(0.22) # ChrBrad_ChrMarine@Walk01 0
points0.append(0.88) # ChrBrad_ChrMarine@WalkCircleLf01_smooth 0
points0.append(0.28) # ChrBrad_ChrMarine@WalkCircleRt01_smooth 0
points0.append(1.09) # ChrBrad_ChrMarine@WalkTightCircleLf01_smooth 0
points0.append(0.26) # ChrBrad_ChrMarine@WalkTightCircleRt01_smooth 0
points0.append(0) # ChrBrad_ChrMarine@Turn360Lf01 0
points0.append(0.70) # ChrBrad_ChrMarine@Turn360Rt01 0
points0.append(0.09) # ChrBrad_ChrMarine@StrafeFastLf01_smooth 0
points0.append(0.43) # ChrBrad_ChrMarine@StrafeFastRt01_smooth 0

statemarineLocomotion.addCorrespondencePoints(motions, points0)
points1 = DoubleVec()
points1.append(0.56) # ChrBrad_ChrMarine@Idle01 1
points1.append(0.42) # ChrBrad_ChrMarine@Jog01 1
points1.append(0.90) # ChrBrad_ChrMarine@Meander01 1
points1.append(0.30) # ChrBrad_ChrMarine@Run01 1
points1.append(0.52) # ChrBrad_ChrMarine@RunCircleLf01_smooth 1
points1.append(0.89) # ChrBrad_ChrMarine@RunCircleRt01_smooth 1
points1.append(0.86) # ChrBrad_ChrMarine@RunTightCircleLf01 1
points1.append(0.54) # ChrBrad_ChrMarine@RunTightCircleRt01 1
points1.append(1.53) # ChrBrad_ChrMarine@StrafeSlowLf01 1
points1.append(0.90) # ChrBrad_ChrMarine@StrafeSlowRt01 1
points1.append(0.72) # ChrBrad_ChrMarine@Walk01 1
points1.append(1.58) # ChrBrad_ChrMarine@WalkCircleLf01_smooth 1
points1.append(0.95) # ChrBrad_ChrMarine@WalkCircleRt01_smooth 1
points1.append(1.80) # ChrBrad_ChrMarine@WalkTightCircleLf01_smooth 1
points1.append(1.00) # ChrBrad_ChrMarine@WalkTightCircleRt01_smooth 1
points1.append(0.70) # ChrBrad_ChrMarine@Idle01 1
points1.append(1.25) # ChrBrad_ChrMarine@Jog01 1
points1.append(0.43) # ChrBrad_ChrMarine@StrafeFastLf01_smooth 1
points1.append(0.88) # ChrBrad_ChrMarine@StrafeFastRt01_smooth 1

statemarineLocomotion.addCorrespondencePoints(motions, points1)
points2 = DoubleVec()
points2.append(1.12) # ChrBrad_ChrMarine@Idle01 2
points2.append(0.75) # ChrBrad_ChrMarine@Jog01 2
points2.append(1.45) # ChrBrad_ChrMarine@Meander01 2
points2.append(0.57) # ChrBrad_ChrMarine@Run01 2
points2.append(0.89) # ChrBrad_ChrMarine@RunCircleLf01_smooth 2
points2.append(1.29) # ChrBrad_ChrMarine@RunCircleRt01_smooth 2
points2.append(1.15) # ChrBrad_ChrMarine@RunTightCircleLf01 2
points2.append(0.86) # ChrBrad_ChrMarine@RunTightCircleRt01 2
points2.append(2.15) # ChrBrad_ChrMarine@StrafeSlowLf01 2
points2.append(1.53) # ChrBrad_ChrMarine@StrafeSlowRt01 2
points2.append(1.22) # ChrBrad_ChrMarine@Walk01 2
points2.append(2.28) # ChrBrad_ChrMarine@WalkCircleLf01_smooth 2
points2.append(1.59) # ChrBrad_ChrMarine@WalkCircleRt01_smooth 2
points2.append(2.47) # ChrBrad_ChrMarine@WalkTightCircleLf01_smooth 2
points2.append(1.82) # ChrBrad_ChrMarine@WalkTightCircleRt01_smooth 2
points2.append(1.29) # ChrBrad_ChrMarine@Idle01 2
points2.append(1.75) # ChrBrad_ChrMarine@Jog01 2
points2.append(0.88) # ChrBrad_ChrMarine@StrafeFastLf01_smooth 2
points2.append(1.24) # ChrBrad_ChrMarine@StrafeFastRt01_smooth 2



statemarineLocomotion.addCorrespondencePoints(motions, points2)
points3 = DoubleVec()
points3.append(1.68) # ChrBrad_ChrMarine@Idle01 3
points3.append(1.07) # ChrBrad_ChrMarine@Jog01 3
points3.append(2.06) # ChrBrad_ChrMarine@Meander01 3
points3.append(0.85) # ChrBrad_ChrMarine@Run01 3
points3.append(1.29) # ChrBrad_ChrMarine@RunCircleLf01_smooth 3
points3.append(1.69) # ChrBrad_ChrMarine@RunCircleRt01_smooth 3
points3.append(1.51) # ChrBrad_ChrMarine@RunTightCircleLf01 3
points3.append(1.15) # ChrBrad_ChrMarine@RunTightCircleRt01 3
points3.append(2.74) # ChrBrad_ChrMarine@StrafeSlowLf01 3
points3.append(2.15) # ChrBrad_ChrMarine@StrafeSlowRt01 3
points3.append(1.74) # ChrBrad_ChrMarine@Walk01 3
points3.append(2.8) # ChrBrad_ChrMarine@WalkCircleLf01_smooth 3
points3.append(2.27) # ChrBrad_ChrMarine@WalkCircleRt01_smooth 3
points3.append(3.22) # ChrBrad_ChrMarine@WalkTightCircleLf01_smooth 3
points3.append(2.45) # ChrBrad_ChrMarine@WalkTightCircleRt01_smooth 3
points3.append(1.68) # ChrBrad_ChrMarine@Idle01 3
points3.append(2.15) # ChrBrad_ChrMarine@Jog01 3
points3.append(1.24) # ChrBrad_ChrMarine@StrafeFastLf01_smooth 3
points3.append(1.69) # ChrBrad_ChrMarine@StrafeFastRt01_smooth 3

statemarineLocomotion.addCorrespondencePoints(motions, points3)
points4 = DoubleVec()
points4.append(2.17) # ChrBrad_ChrMarine@Idle01 4
points4.append(1.40) # ChrBrad_ChrMarine@Jog01 4
points4.append(2.54) # ChrBrad_ChrMarine@Meander01 4
points4.append(1.07) # ChrBrad_ChrMarine@Run01 4
points4.append(1.69) # ChrBrad_ChrMarine@RunCircleLf01_smooth 4
points4.append(2.09) # ChrBrad_ChrMarine@RunCircleRt01_smooth 4
points4.append(1.91) # ChrBrad_ChrMarine@RunTightCircleLf01 4
points4.append(1.44) # ChrBrad_ChrMarine@RunTightCircleRt01 4
points4.append(3.17) # ChrBrad_ChrMarine@StrafeFastLf01_smooth 4
points4.append(2.74) # ChrBrad_ChrMarine@StrafeFastRt01_smooth 4
points4.append(2.29) # ChrBrad_ChrMarine@Walk01 4
points4.append(3.48) # ChrBrad_ChrMarine@WalkCircleLf01_smooth 4
points4.append(2.88) # ChrBrad_ChrMarine@WalkCircleRt01_smooth 4
points4.append(4.02) # ChrBrad_ChrMarine@WalkTightCircleLf01_smooth 4
points4.append(3.19) # ChrBrad_ChrMarine@WalkTightCircleRt01_smooth 4
points4.append(2.13) # ChrBrad_ChrMarine@Idle01 4
points4.append(2.83) # ChrBrad_ChrMarine@Jog01 4
points4.append(1.69) # ChrBrad_ChrMarine@StrafeSlowLf01 4
points4.append(2.03) # ChrBrad_ChrMarine@StrafeSlowRt01 4

statemarineLocomotion.addCorrespondencePoints(motions, points4)

skeleton = scene.getSkeleton("ChrBrad.sk")
joint = skeleton.getJointByName("base")
travelDirection = ([0, 0, 0, 0, 0, 0, 0, 0, -1, 1, 0, 0, 0, 0 ,0, 0, 0, -1, 1 ])

for i in range(0, len(motions)):
	motion = scene.getMotion(motions[i])
	motion.connect(skeleton)
	correspondancePoints = statemarineLocomotion.getCorrespondancePoints(i)
	lenCorrespondancePoints = len(correspondancePoints)
	#speed = motion.getJointSpeed(joint, correspondancePoints[0], correspondancePoints[lenCorrespondancePoints - 1])
	#omega = motion.getJointAngularSpeed(joint, correspondancePoints[0], correspondancePoints[lenCorrespondancePoints - 1])
	speed = motion.getJointSpeed(joint, 0, motion.getDuration())
	#speedZ = motion.getJointSpeedAxis(joint, "Z", 0, motion.getDuration())
	if (travelDirection[i] != 0):
		direction = motion.getJointSpeedAxis(joint, "X", 0, motion.getDuration())
	else:
		direction = travelDirection[i]
	
	omega = motion.getJointAngularSpeed(joint, 0, motion.getDuration())
	
	statemarineLocomotion.setParameter(motions[i], speed, omega, direction)
	print "Motion " + motion.getName() + " (" + str(speed) + ", " + str(omega) + ", " + str(direction) + ")"
	motion.disconnect()
	
	
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Idle01", "ChrBrad_ChrMarine@Meander01", "ChrBrad_ChrMarine@StrafeSlowRt01", "ChrBrad_ChrMarine@WalkCircleLf01_smooth")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Idle01", "ChrBrad_ChrMarine@StrafeSlowRt01", "ChrBrad_ChrMarine@WalkCircleLf01_smooth", "ChrBrad_ChrMarine@WalkTightCircleLf01_smooth")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Idle01", "ChrBrad_ChrMarine@StrafeSlowRt01", "ChrBrad_ChrMarine@WalkTightCircleLf01_smooth", "ChrBrad_ChrMarine@Turn360Lf01")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@RunTightCircleLf01", "ChrBrad_ChrMarine@StrafeSlowRt01", "ChrBrad_ChrMarine@WalkTightCircleLf01_smooth", "ChrBrad_ChrMarine@Turn360Lf01")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@RunTightCircleLf01", "ChrBrad_ChrMarine@StrafeSlowRt01", "ChrBrad_ChrMarine@WalkCircleLf01_smooth", "ChrBrad_ChrMarine@WalkTightCircleLf01_smooth")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Meander01", "ChrBrad_ChrMarine@StrafeFastRt01_smooth", "ChrBrad_ChrMarine@Walk01", "ChrBrad_ChrMarine@WalkCircleLf01_smooth")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Meander01", "ChrBrad_ChrMarine@StrafeSlowRt01", "ChrBrad_ChrMarine@StrafeFastRt01_smooth", "ChrBrad_ChrMarine@WalkCircleLf01_smooth")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@RunTightCircleLf01", "ChrBrad_ChrMarine@StrafeSlowRt01", "ChrBrad_ChrMarine@StrafeFastRt01_smooth", "ChrBrad_ChrMarine@WalkCircleLf01_smooth")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Jog01", "ChrBrad_ChrMarine@StrafeFastRt01_smooth", "ChrBrad_ChrMarine@Walk01", "ChrBrad_ChrMarine@WalkCircleLf01_smooth")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Jog01", "ChrBrad_ChrMarine@RunTightCircleLf01", "ChrBrad_ChrMarine@StrafeFastRt01_smooth", "ChrBrad_ChrMarine@WalkCircleLf01_smooth")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Jog01", "ChrBrad_ChrMarine@RunCircleLf01_smooth", "ChrBrad_ChrMarine@RunTightCircleLf01", "ChrBrad_ChrMarine@StrafeFastRt01_smooth")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Jog01", "ChrBrad_ChrMarine@Run01", "ChrBrad_ChrMarine@RunCircleLf01_smooth", "ChrBrad_ChrMarine@StrafeFastRt01_smooth")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@RunTightCircleLf01", "ChrBrad_ChrMarine@Run01", "ChrBrad_ChrMarine@RunCircleLf01_smooth", "ChrBrad_ChrMarine@StrafeFastRt01_smooth")

statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Idle01", "ChrBrad_ChrMarine@Meander01", "ChrBrad_ChrMarine@StrafeSlowLf01", "ChrBrad_ChrMarine@WalkCircleLf01_smooth")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Idle01", "ChrBrad_ChrMarine@StrafeSlowLf01", "ChrBrad_ChrMarine@WalkCircleLf01_smooth", "ChrBrad_ChrMarine@WalkTightCircleLf01_smooth")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Idle01", "ChrBrad_ChrMarine@StrafeSlowLf01", "ChrBrad_ChrMarine@WalkTightCircleLf01_smooth", "ChrBrad_ChrMarine@Turn360Lf01")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@RunTightCircleLf01", "ChrBrad_ChrMarine@StrafeSlowLf01", "ChrBrad_ChrMarine@WalkTightCircleLf01_smooth", "ChrBrad_ChrMarine@Turn360Lf01")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@RunTightCircleLf01", "ChrBrad_ChrMarine@StrafeSlowLf01", "ChrBrad_ChrMarine@WalkCircleLf01_smooth", "ChrBrad_ChrMarine@WalkTightCircleLf01_smooth")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Meander01", "ChrBrad_ChrMarine@StrafeFastLf01_smooth", "ChrBrad_ChrMarine@Walk01", "ChrBrad_ChrMarine@WalkCircleLf01_smooth")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Meander01", "ChrBrad_ChrMarine@StrafeSlowLf01", "ChrBrad_ChrMarine@StrafeFastLf01_smooth", "ChrBrad_ChrMarine@WalkCircleLf01_smooth")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@RunTightCircleLf01", "ChrBrad_ChrMarine@StrafeSlowLf01", "ChrBrad_ChrMarine@StrafeFastLf01_smooth", "ChrBrad_ChrMarine@WalkCircleLf01_smooth")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Jog01", "ChrBrad_ChrMarine@StrafeFastLf01_smooth", "ChrBrad_ChrMarine@Walk01", "ChrBrad_ChrMarine@WalkCircleLf01_smooth")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Jog01", "ChrBrad_ChrMarine@RunTightCircleLf01", "ChrBrad_ChrMarine@StrafeFastLf01_smooth", "ChrBrad_ChrMarine@WalkCircleLf01_smooth")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Jog01", "ChrBrad_ChrMarine@RunCircleLf01_smooth", "ChrBrad_ChrMarine@RunTightCircleLf01", "ChrBrad_ChrMarine@StrafeFastLf01_smooth")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Jog01", "ChrBrad_ChrMarine@Run01", "ChrBrad_ChrMarine@RunCircleLf01_smooth", "ChrBrad_ChrMarine@StrafeFastLf01_smooth")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@RunTightCircleLf01", "ChrBrad_ChrMarine@Run01", "ChrBrad_ChrMarine@RunCircleLf01_smooth", "ChrBrad_ChrMarine@StrafeFastLf01_smooth")

statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Idle01", "ChrBrad_ChrMarine@Meander01", "ChrBrad_ChrMarine@StrafeSlowRt01", "ChrBrad_ChrMarine@WalkCircleRt01_smooth")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Idle01", "ChrBrad_ChrMarine@StrafeSlowRt01", "ChrBrad_ChrMarine@WalkCircleRt01_smooth", "ChrBrad_ChrMarine@WalkTightCircleRt01_smooth")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Idle01", "ChrBrad_ChrMarine@StrafeSlowRt01", "ChrBrad_ChrMarine@WalkTightCircleRt01_smooth", "ChrBrad_ChrMarine@Turn360Rt01")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@RunTightCircleRt01", "ChrBrad_ChrMarine@StrafeSlowRt01", "ChrBrad_ChrMarine@WalkTightCircleRt01_smooth", "ChrBrad_ChrMarine@Turn360Rt01")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@RunTightCircleRt01", "ChrBrad_ChrMarine@StrafeSlowRt01", "ChrBrad_ChrMarine@WalkCircleRt01_smooth", "ChrBrad_ChrMarine@WalkTightCircleRt01_smooth")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Meander01", "ChrBrad_ChrMarine@StrafeFastRt01_smooth", "ChrBrad_ChrMarine@Walk01", "ChrBrad_ChrMarine@WalkCircleRt01_smooth")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Meander01", "ChrBrad_ChrMarine@StrafeSlowRt01", "ChrBrad_ChrMarine@StrafeFastRt01_smooth", "ChrBrad_ChrMarine@WalkCircleRt01_smooth")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@RunTightCircleRt01", "ChrBrad_ChrMarine@StrafeSlowRt01", "ChrBrad_ChrMarine@StrafeFastRt01_smooth", "ChrBrad_ChrMarine@WalkCircleRt01_smooth")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Jog01", "ChrBrad_ChrMarine@StrafeFastRt01_smooth", "ChrBrad_ChrMarine@Walk01", "ChrBrad_ChrMarine@WalkCircleRt01_smooth")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Jog01", "ChrBrad_ChrMarine@RunTightCircleRt01", "ChrBrad_ChrMarine@StrafeFastRt01_smooth", "ChrBrad_ChrMarine@WalkCircleRt01_smooth")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Jog01", "ChrBrad_ChrMarine@RunCircleRt01_smooth", "ChrBrad_ChrMarine@RunTightCircleRt01", "ChrBrad_ChrMarine@StrafeFastRt01_smooth")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Jog01", "ChrBrad_ChrMarine@Run01", "ChrBrad_ChrMarine@RunCircleRt01_smooth", "ChrBrad_ChrMarine@StrafeFastRt01_smooth")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@RunTightCircleRt01", "ChrBrad_ChrMarine@Run01", "ChrBrad_ChrMarine@RunCircleRt01_smooth", "ChrBrad_ChrMarine@StrafeFastRt01_smooth")

statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Idle01", "ChrBrad_ChrMarine@Meander01", "ChrBrad_ChrMarine@StrafeSlowLf01", "ChrBrad_ChrMarine@WalkCircleRt01_smooth")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Idle01", "ChrBrad_ChrMarine@StrafeSlowLf01", "ChrBrad_ChrMarine@WalkCircleRt01_smooth", "ChrBrad_ChrMarine@WalkTightCircleRt01_smooth")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Idle01", "ChrBrad_ChrMarine@StrafeSlowLf01", "ChrBrad_ChrMarine@WalkTightCircleRt01_smooth", "ChrBrad_ChrMarine@Turn360Rt01")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@RunTightCircleRt01", "ChrBrad_ChrMarine@StrafeSlowLf01", "ChrBrad_ChrMarine@WalkTightCircleRt01_smooth", "ChrBrad_ChrMarine@Turn360Rt01")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@RunTightCircleRt01", "ChrBrad_ChrMarine@StrafeSlowLf01", "ChrBrad_ChrMarine@WalkCircleRt01_smooth", "ChrBrad_ChrMarine@WalkTightCircleRt01_smooth")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Meander01", "ChrBrad_ChrMarine@StrafeFastLf01_smooth", "ChrBrad_ChrMarine@Walk01", "ChrBrad_ChrMarine@WalkCircleRt01_smooth")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Meander01", "ChrBrad_ChrMarine@StrafeSlowLf01", "ChrBrad_ChrMarine@StrafeFastLf01_smooth", "ChrBrad_ChrMarine@WalkCircleRt01_smooth")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@RunTightCircleRt01", "ChrBrad_ChrMarine@StrafeSlowLf01", "ChrBrad_ChrMarine@StrafeFastLf01_smooth", "ChrBrad_ChrMarine@WalkCircleRt01_smooth")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Jog01", "ChrBrad_ChrMarine@StrafeFastLf01_smooth", "ChrBrad_ChrMarine@Walk01", "ChrBrad_ChrMarine@WalkCircleRt01_smooth")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Jog01", "ChrBrad_ChrMarine@RunTightCircleRt01", "ChrBrad_ChrMarine@StrafeFastLf01_smooth", "ChrBrad_ChrMarine@WalkCircleRt01_smooth")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Jog01", "ChrBrad_ChrMarine@RunCircleRt01_smooth", "ChrBrad_ChrMarine@RunTightCircleRt01", "ChrBrad_ChrMarine@StrafeFastLf01_smooth")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Jog01", "ChrBrad_ChrMarine@Run01", "ChrBrad_ChrMarine@RunCircleRt01_smooth", "ChrBrad_ChrMarine@StrafeFastLf01_smooth")
statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@RunTightCircleRt01", "ChrBrad_ChrMarine@Run01", "ChrBrad_ChrMarine@RunCircleRt01_smooth", "ChrBrad_ChrMarine@StrafeFastLf01_smooth")

	
# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Idle01", "ChrBrad_ChrMarine@Meander01", "ChrBrad_ChrMarine@StrafeFastLf01_smooth", "ChrBrad_ChrMarine@WalkCircleLf01_smooth")
# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Idle01", "ChrBrad_ChrMarine@StrafeFastLf01_smooth", "ChrBrad_ChrMarine@WalkCircleLf01_smooth", "ChrBrad_ChrMarine@WalkTightCircleLf01_smooth")
# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Meander01", "ChrBrad_ChrMarine@StrafeFastLf01_smooth", "ChrBrad_ChrMarine@Walk01", "ChrBrad_ChrMarine@WalkCircleLf01_smooth")
# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@RunTightCircleLf01", "ChrBrad_ChrMarine@StrafeFastLf01_smooth", "ChrBrad_ChrMarine@Walk01", "ChrBrad_ChrMarine@WalkCircleLf01_smooth")
# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@RunTightCircleLf01", "ChrBrad_ChrMarine@StrafeFastLf01_smooth", "ChrBrad_ChrMarine@WalkCircleLf01_smooth", "ChrBrad_ChrMarine@WalkTightCircleLf01_smooth")
# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@RunCircleLf01_smooth", "ChrBrad_ChrMarine@RunTightCircleLf01", "ChrBrad_ChrMarine@StrafeFastLf01_smooth", "ChrBrad_ChrMarine@Walk01")
# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Jog01", "ChrBrad_ChrMarine@RunCircleLf01_smooth", "ChrBrad_ChrMarine@StrafeFastLf01_smooth", "ChrBrad_ChrMarine@Walk01")
# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Jog01", "ChrBrad_ChrMarine@Run01", "ChrBrad_ChrMarine@RunCircleLf01_smooth", "ChrBrad_ChrMarine@StrafeFastLf01_smooth")
# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Run01", "ChrBrad_ChrMarine@RunCircleLf01_smooth", "ChrBrad_ChrMarine@RunTightCircleLf01", "ChrBrad_ChrMarine@StrafeFastLf01_smooth")
# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Idle01", "ChrBrad_ChrMarine@StrafeFastLf01_smooth", "ChrBrad_ChrMarine@WalkTightCircleLf01_smooth", "ChrBrad_ChrMarine@Turn360Lf01")
# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@RunTightCircleLf01", "ChrBrad_ChrMarine@StrafeFastLf01_smooth", "ChrBrad_ChrMarine@WalkTightCircleLf01_smooth", "ChrBrad_ChrMarine@Turn360Lf01")
#statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@RunTightCircleLf01", "ChrBrad_ChrMarine@StrafeFastLf01_smooth", "ChrBrad_ChrMarine@Run01", "ChrBrad_ChrMarine@Turn360Lf01")

# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Idle01", "ChrBrad_ChrMarine@Meander01", "ChrBrad_ChrMarine@StrafeFastRt01_smooth", "ChrBrad_ChrMarine@WalkCircleLf01_smooth")
# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Idle01", "ChrBrad_ChrMarine@StrafeFastRt01_smooth", "ChrBrad_ChrMarine@WalkCircleLf01_smooth", "ChrBrad_ChrMarine@WalkTightCircleLf01_smooth")
# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Meander01", "ChrBrad_ChrMarine@StrafeFastRt01_smooth", "ChrBrad_ChrMarine@Walk01", "ChrBrad_ChrMarine@WalkCircleLf01_smooth")
# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@RunTightCircleLf01", "ChrBrad_ChrMarine@StrafeFastRt01_smooth", "ChrBrad_ChrMarine@Walk01", "ChrBrad_ChrMarine@WalkCircleLf01_smooth")
# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@RunTightCircleLf01", "ChrBrad_ChrMarine@StrafeFastRt01_smooth", "ChrBrad_ChrMarine@WalkCircleLf01_smooth", "ChrBrad_ChrMarine@WalkTightCircleLf01_smooth")
# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@RunCircleLf01_smooth", "ChrBrad_ChrMarine@RunTightCircleLf01", "ChrBrad_ChrMarine@StrafeFastRt01_smooth", "ChrBrad_ChrMarine@Walk01")
# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Jog01", "ChrBrad_ChrMarine@RunCircleLf01_smooth", "ChrBrad_ChrMarine@StrafeFastRt01_smooth", "ChrBrad_ChrMarine@Walk01")
# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Jog01", "ChrBrad_ChrMarine@Run01", "ChrBrad_ChrMarine@RunCircleLf01_smooth", "ChrBrad_ChrMarine@StrafeFastRt01_smooth")
# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Run01", "ChrBrad_ChrMarine@RunCircleLf01_smooth", "ChrBrad_ChrMarine@RunTightCircleLf01", "ChrBrad_ChrMarine@StrafeFastRt01_smooth")
# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Idle01", "ChrBrad_ChrMarine@StrafeFastRt01_smooth", "ChrBrad_ChrMarine@WalkTightCircleLf01_smooth", "ChrBrad_ChrMarine@Turn360Lf01")
# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@RunTightCircleLf01", "ChrBrad_ChrMarine@StrafeFastRt01_smooth", "ChrBrad_ChrMarine@WalkTightCircleLf01_smooth", "ChrBrad_ChrMarine@Turn360Lf01")
#statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@RunTightCircleLf01", "ChrBrad_ChrMarine@StrafeFastRt01_smooth", "ChrBrad_ChrMarine@Run01", "ChrBrad_ChrMarine@Turn360Lf01")

# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Idle01", "ChrBrad_ChrMarine@Meander01", "ChrBrad_ChrMarine@StrafeFastLf01_smooth", "ChrBrad_ChrMarine@WalkCircleRt01_smooth")
# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Idle01", "ChrBrad_ChrMarine@StrafeFastLf01_smooth", "ChrBrad_ChrMarine@WalkCircleRt01_smooth", "ChrBrad_ChrMarine@WalkTightCircleRt01_smooth")
# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Meander01", "ChrBrad_ChrMarine@StrafeFastLf01_smooth", "ChrBrad_ChrMarine@Walk01", "ChrBrad_ChrMarine@WalkCircleRt01_smooth")
# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@RunTightCircleRt01", "ChrBrad_ChrMarine@StrafeFastLf01_smooth", "ChrBrad_ChrMarine@Walk01", "ChrBrad_ChrMarine@WalkCircleRt01_smooth")
# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@RunTightCircleRt01", "ChrBrad_ChrMarine@StrafeFastLf01_smooth", "ChrBrad_ChrMarine@WalkCircleRt01_smooth", "ChrBrad_ChrMarine@WalkTightCircleRt01_smooth")
# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@RunCircleRt01_smooth", "ChrBrad_ChrMarine@RunTightCircleRt01", "ChrBrad_ChrMarine@StrafeFastLf01_smooth", "ChrBrad_ChrMarine@Walk01")
# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Jog01", "ChrBrad_ChrMarine@RunCircleRt01_smooth", "ChrBrad_ChrMarine@StrafeFastLf01_smooth", "ChrBrad_ChrMarine@Walk01")
# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Jog01", "ChrBrad_ChrMarine@Run01", "ChrBrad_ChrMarine@RunCircleRt01_smooth", "ChrBrad_ChrMarine@StrafeFastLf01_smooth")
# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Run01", "ChrBrad_ChrMarine@RunCircleRt01_smooth", "ChrBrad_ChrMarine@RunTightCircleRt01", "ChrBrad_ChrMarine@StrafeFastLf01_smooth")
# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Idle01", "ChrBrad_ChrMarine@StrafeFastLf01_smooth", "ChrBrad_ChrMarine@WalkTightCircleRt01_smooth", "ChrBrad_ChrMarine@Turn360Rt01")
# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@RunTightCircleRt01", "ChrBrad_ChrMarine@StrafeFastLf01_smooth", "ChrBrad_ChrMarine@WalkTightCircleRt01_smooth", "ChrBrad_ChrMarine@Turn360Rt01")

# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Idle01", "ChrBrad_ChrMarine@Meander01", "ChrBrad_ChrMarine@StrafeFastRt01_smooth", "ChrBrad_ChrMarine@WalkCircleRt01_smooth")
# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Idle01", "ChrBrad_ChrMarine@StrafeFastRt01_smooth", "ChrBrad_ChrMarine@WalkCircleRt01_smooth", "ChrBrad_ChrMarine@WalkTightCircleRt01_smooth")
# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Meander01", "ChrBrad_ChrMarine@StrafeFastRt01_smooth", "ChrBrad_ChrMarine@Walk01", "ChrBrad_ChrMarine@WalkCircleRt01_smooth")
# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@RunTightCircleRt01", "ChrBrad_ChrMarine@StrafeFastRt01_smooth", "ChrBrad_ChrMarine@Walk01", "ChrBrad_ChrMarine@WalkCircleRt01_smooth")
# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@RunTightCircleRt01", "ChrBrad_ChrMarine@StrafeFastRt01_smooth", "ChrBrad_ChrMarine@WalkCircleRt01_smooth", "ChrBrad_ChrMarine@WalkTightCircleRt01_smooth")
# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@RunCircleRt01_smooth", "ChrBrad_ChrMarine@RunTightCircleRt01", "ChrBrad_ChrMarine@StrafeFastRt01_smooth", "ChrBrad_ChrMarine@Walk01")
# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Jog01", "ChrBrad_ChrMarine@RunCircleRt01_smooth", "ChrBrad_ChrMarine@StrafeFastRt01_smooth", "ChrBrad_ChrMarine@Walk01")
# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Jog01", "ChrBrad_ChrMarine@Run01", "ChrBrad_ChrMarine@RunCircleRt01_smooth", "ChrBrad_ChrMarine@StrafeFastRt01_smooth")
# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Run01", "ChrBrad_ChrMarine@RunCircleRt01_smooth", "ChrBrad_ChrMarine@RunTightCircleRt01", "ChrBrad_ChrMarine@StrafeFastRt01_smooth")
# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@Idle01", "ChrBrad_ChrMarine@StrafeFastRt01_smooth", "ChrBrad_ChrMarine@WalkTightCircleRt01_smooth", "ChrBrad_ChrMarine@Turn360Rt01")
# statemarineLocomotion.addTetrahedron("ChrBrad_ChrMarine@RunTightCircleRt01", "ChrBrad_ChrMarine@StrafeFastRt01_smooth", "ChrBrad_ChrMarine@WalkTightCircleRt01_smooth", "ChrBrad_ChrMarine@Turn360Rt01")

