# state ChrMarineStep
# autogenerated by SmartBody

stateManager = scene.getStateManager()

stateChrMarineStep = stateManager.createState2D("ChrMarineStep")

motions = StringVec()
motions.append("ChrBrad_ChrMarine@Idle01")
motions.append("ChrBrad_ChrMarine@Idle01_StepBackwardsLf01")
motions.append("ChrBrad_ChrMarine@Idle01_StepBackwardsRt01")
motions.append("ChrBrad_ChrMarine@Idle01_StepForwardLf01")
motions.append("ChrBrad_ChrMarine@Idle01_StepForwardRt01")
motions.append("ChrBrad_ChrMarine@Idle01_StepSidewaysLf01")
motions.append("ChrBrad_ChrMarine@Idle01_StepSidewaysRt01")

paramsX = DoubleVec()
paramsY = DoubleVec()
paramsX.append(8.31458e-005) # ChrBrad_ChrMarine@Idle01 X
paramsY.append(-6.8546e-005) # ChrBrad_ChrMarine@Idle01 Y
paramsX.append(0.0) # ChrBrad_ChrMarine@Idle01_StepBackwardsLf01 X
paramsY.append(-0.349858) # ChrBrad_ChrMarine@Idle01_StepBackwardsLf01 Y
paramsX.append(0.0) # ChrBrad_ChrMarine@Idle01_StepBackwardsRt01 X
paramsY.append(-0.349858) # ChrBrad_ChrMarine@Idle01_StepBackwardsRt01 Y
paramsX.append(-0.0225843) # ChrBrad_ChrMarine@Idle01_StepForwardLf01 X
paramsY.append(0.535643) # ChrBrad_ChrMarine@Idle01_StepForwardLf01 Y
paramsX.append(0.0234374) # ChrBrad_ChrMarine@Idle01_StepForwardRt01 X
paramsY.append(0.535643) # ChrBrad_ChrMarine@Idle01_StepForwardRt01 Y
paramsX.append(-0.234709) # ChrBrad_ChrMarine@Idle01_StepSidewaysLf01 X
paramsY.append(-0.010002) # ChrBrad_ChrMarine@Idle01_StepSidewaysLf01 Y
paramsX.append(0.234693) # ChrBrad_ChrMarine@Idle01_StepSidewaysRt01 X
paramsY.append(-0.010002) # ChrBrad_ChrMarine@Idle01_StepSidewaysRt01 Y
for i in range(0, len(motions)):
	stateChrMarineStep.addMotion(motions[i], paramsX[i], paramsY[i])

points0 = DoubleVec()
points0.append(0) # ChrBrad_ChrMarine@Idle01 0
points0.append(0) # ChrBrad_ChrMarine@Idle01_StepBackwardsLf01 0
points0.append(0) # ChrBrad_ChrMarine@Idle01_StepBackwardsRt01 0
points0.append(0) # ChrBrad_ChrMarine@Idle01_StepForwardLf01 0
points0.append(0) # ChrBrad_ChrMarine@Idle01_StepForwardRt01 0
points0.append(0) # ChrBrad_ChrMarine@Idle01_StepSidewaysLf01 0
points0.append(0) # ChrBrad_ChrMarine@Idle01_StepSidewaysRt01 0
stateChrMarineStep.addCorrespondencePoints(motions, points0)
points1 = DoubleVec()
points1.append(1.1153) # ChrBrad_ChrMarine@Idle01 1
points1.append(0.68) # ChrBrad_ChrMarine@Idle01_StepBackwardsLf01 1
points1.append(0.68) # ChrBrad_ChrMarine@Idle01_StepBackwardsRt01 1
points1.append(1.02258) # ChrBrad_ChrMarine@Idle01_StepForwardLf01 1
points1.append(1.0303) # ChrBrad_ChrMarine@Idle01_StepForwardRt01 1
points1.append(0.821667) # ChrBrad_ChrMarine@Idle01_StepSidewaysLf01 1
points1.append(0.824242) # ChrBrad_ChrMarine@Idle01_StepSidewaysRt01 1
stateChrMarineStep.addCorrespondencePoints(motions, points1)
points2 = DoubleVec()
points2.append(2.165) # ChrBrad_ChrMarine@Idle01 2
points2.append(1.32) # ChrBrad_ChrMarine@Idle01_StepBackwardsLf01 2
points2.append(1.32) # ChrBrad_ChrMarine@Idle01_StepBackwardsRt01 2
points2.append(1.985) # ChrBrad_ChrMarine@Idle01_StepForwardLf01 2
points2.append(2) # ChrBrad_ChrMarine@Idle01_StepForwardRt01 2
points2.append(1.595) # ChrBrad_ChrMarine@Idle01_StepSidewaysLf01 2
points2.append(1.6) # ChrBrad_ChrMarine@Idle01_StepSidewaysRt01 2
stateChrMarineStep.addCorrespondencePoints(motions, points2)

stateChrMarineStep.addTriangle("ChrBrad_ChrMarine@Idle01", "ChrBrad_ChrMarine@Idle01_StepBackwardsLf01", "ChrBrad_ChrMarine@Idle01_StepSidewaysLf01")
stateChrMarineStep.addTriangle("ChrBrad_ChrMarine@Idle01", "ChrBrad_ChrMarine@Idle01_StepForwardLf01", "ChrBrad_ChrMarine@Idle01_StepSidewaysLf01")
stateChrMarineStep.addTriangle("ChrBrad_ChrMarine@Idle01", "ChrBrad_ChrMarine@Idle01_StepBackwardsRt01", "ChrBrad_ChrMarine@Idle01_StepSidewaysRt01")
stateChrMarineStep.addTriangle("ChrBrad_ChrMarine@Idle01", "ChrBrad_ChrMarine@Idle01_StepForwardRt01", "ChrBrad_ChrMarine@Idle01_StepSidewaysRt01")
